language: rust

rust:
    - stable
    - nightly  

matrix:
    allow_failures:
        -rust: nightly
        
before_install:
    - sudo apt-get install libasound2-dev --yes
    - sudo apt-get update
